yolo_pipeline:
  raw_data_dir: raw_yolo_data
  classes_file: yolo_class_names.txt
  class_names:
  - frostbolt_ready
  - frostbolt_cooldown
  - icelance_ready
  - icelance_cooldown
  - frozenorb_ready
  - frozenorb_cooldown
yolo_training:
  output_dir: yolo_dataset
  split_ratio: 0.8
  epochs: 50
  model: yolov8n.pt
  imgsz: 640
yolo_model_path: runs/detect/train/weights/best.pt
screen_capture_region: null
keystroke_sender:
  type: pynput
  keypress_delay_ms: 50
current_strategy: strategies/frostfire_mage.yaml
mode_switch_keys:
  aoe_mode: f1
  single_target_mode: f2
  stop_casting: f3
